# Site settings
title: NetworkedPlanet
email: contact@networkedplanet.com
description: Experts in Linked and Open Data Publishing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://networkedplanet.com" # the base hostname & protocol for your site
twitter: "@nwplanet"
twitter_image: http://networkedplanet.com/assets/images/np-220px.png

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    
collections:
    solutions:
        output: true
    glossary:
        output: true
    training:
        output: true
        permalink: /training/:path/

permalink: /blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: "/blog/page:num/"
tag_dir: "/blog/tags"
